# The Problem
<!-- 
Outlining the issue / weak point / problem to be solved by this proposal. This should be a compelling section that sets the reader up for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Who it affects
 - [ ] Have there been previous attempts to resolve the problem
 - [ ] Why it should be tackled
-->

Despite more than 20 years of existence, the CRAN archive has had a [persistently low percentage of female authors and package maintainers](http://www.pnas.org/content/112/48/14788.abstract). In recent scraping and analysis of package DESCRIPTION files, it is estimated that [fewer than 15% of R packages are maintained by women](http://forwards.github.io/data/#packages). Steps have been taken to acknowledge female contributions in the R community, by inviting new members into the R Foundation, and ensuring that the invited speaker list at recent useR! conferences includes women who have made an impact. The fundamental problem for building female participation in the community, though, seems to be in coding. With support of R Consortium funding we can make a grass roots change by developing R coding skills in girls and R package development knowledge among women.
