# Forwards Workshops for Women and Girls
<!--
This is where the proposal should be outlined. 
-->

### Overview
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->

This proposal is for funding to support the development of coding skills for increasing the participation of women in the R community. There are two levels of action:

1. Building the package development skills of women in the research community, to encourage them to distribute their research as an R package.
2. Developing an interest in coding among teenage girls. 

Funding is sought to provide support to conduct workshops at these two levels. We will coordinate with R-Ladies organisations across the globe, and faculty at a variety of institutions. The funds will be used to support travel of participants from geographically dispersed regions on the country to ensure inclusion of socio-economically disadvantaged women. Funds are also sought to provide catering to ensure that the learning environment is comfortable for participants. The tutors will fund their own travel and we will work with local organisers to obtain facilities at no cost. 

### Detail
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->

### Workshops for Women

 - Materials will build on existing material donated by Hadley Wickham, Jenny Bryan and Di Cook and will be used and extended under a creative commons license. 
 - The focus is on packaging code, using GitHub and submission to CRAN. 
 - Workshops will be conducted in several locations world-wide, currently aiming for Australia (Melbourne), New Zealand (Auckland), USA and Europe. 

<!--
 Workshops for women will re-use existing material contributed by Hadley, based on Master R Developer workshops (second day only). This will be made available to members of Forwards taskforce and others from the R Community for the sole purpose of running workshops targeted at under-represented groups [must be free to participants? Tutors must be volunteers?]. Hadley maintains copyright and full ownership of the materials.
 - Tutors agree to donate their time, but expenses are covered. As course material is already prepared, volunteer time is restricted to the workshop itself.
 - 3 workshops will be run, in NZ, US and EU, to tie in with R/statistical computing/statistics conferences that tutors already plan to attend. In this way no travel funding is required for tutors and the potential audience is maximised, with many attendees able to justify funding travel to both workshop and conference.
 - Therefore only expenses are additional night(s) accommodation of tutors and per diem for travel and subsistence; tea/coffee breaks and lunch for all participants. Additional funding is included to contribute to travel/accommodation expenses for people that need additional financial support.
-->

### Workshops for Girls

 - Materials will be developed for encouraging teenage girls to start coding in R.
 - The focus will be on developing Shiny apps, web scraping, and making plots of data. 
 - A selection of topics related to contemporary current affairs will be used, e.g. girls sports.
 - Materials will build on existing material donated by Di Cook, based on working with Melbourne High School students on pedestrian sensor data, and will be used and extended under a creative commons license.  

<!--
 Girl's workshop will be run on same principle, but new material needs to be developed for this, which will be developed by Di/Hadley/Jenny. Part of the funding will go to this. Afterwards material will be made available to members of Forwards taskforce and others from the R Community for the sole purpose of running similar outreach events [similar conditions as above].
 - It is assumed in this case, groups of girls will travel up for the day at low cost (e.g. coach travel) so can self-fund as a usual school trip.
-->

### Volunteers

- The workshop presenters will donate their time and, as possible,  cover their costs to travel to the location.
- Tutors will be recruited from local institutions to help with the hands-on coding. They will donate their time to assist, but may be funded for travel as needed.
