# Success
<!-- 
Projects should have a definition of done that is measurable, and a thorough understanding going in of what the risks are to delivery 
-->

### Definition of done
<!-- 
What does success look like? 
-->

- Successful operation of workshops in Melbourne, Auckland, USA and Europe.
- Workshop materials distributed for others to use on the Forwards web site. 

### Measuring success
<!-- 
How will we know when success is achieved, what markers can we use along the way 
-->
- The Forwards diversity sub-committee is maintaining statistics on participation of women and under-represented groups in the R community. We will track these to examine the effect of the workshops on improving the numbers. Of particular interest is the proportion of female package maintainers and authors. 
- A participant survey will be constructed before the first workshop to obtain feedback. A summary of this feedback will be published on the Forwards web site. Of particular interest is that a high proportion of participants would recommend attending the workshop to their friends, and colleagues. 
- Additional workshops, using the materials developed, are offered by new groups, such as R-Ladies Hobart, Buenos Aires, Tbilisi, ... would be hugely encouraging. 
- R packages and R Journal articles submitted by attendees, which we might be able to track by encouraging notes to be added in the github wiki. 


### Future work
<!-- 
How could this be extended / developed in the future by yourself and/or the community in general?
-->

- The workshop materials will be made freely available on the web, with a creative commons license. Others will be able to build on these and contribute back. Metrics on downloads and usage of materials would be available.
- Future workshops will become cheaper to hold. Sponsorship will be sought from larger local organisations and businesses. For example, Qantas or ANZ bank have programs that may be able to support the Australian workshops to bring participants from rural areas or fund tutors travel to remote locations to run workshops, with an illustration of the benefit provided by the initial series. 

### Key risks
<!-- 
What sort of things could come up that can delay or break the project?

 - [ ] People
 - [ ] Processes
 - [ ] Tooling & Technology
 - [ ] Costs

-->
This is a low risk project. There is already a base of material to build on, from workshops delivered by Hadley Wickham and course material from Jenny Bryan and Di Cook used in University classes. There is little risk that the new materials would not be developed. We are expecting for some participants to travel to workshops, and there are always risks associated with travel. It may be necessary for instructors and tutors to have police background checks in order to work with high school students, and this will need to be organised with the local committees.

