# Project plan

## Start-up phase
<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

Mar-Jul 2017 Materials development and feedback solicitation from the community

## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

- Jul-Nov 2017 Trial workshops under the R-Ladies Melbourne umbrella. Di will run these workshops with student volunteers from Monash University.
- Dec 2017 Both workshops conducted before IASC 2017 in Auckland, NZ. IASC 2017 is honouring Ross Ihaka's contributions and retirement. Di, Hadley and Jenny are planning on being at IASC and will travel a few days ahead to conduct the workshops.
- 2018 Locations in USA to be determined, spearheaded by Jenny Bryan, Joyce Robbins and Andrea Foulkes
- 2018 Locations in Europe to be determined, spearheaded by Heather Turner and Isabella Gollini

The package development workshops will be organised around suitable events, e.g. eRum, WSDS. For these we assume the same running costs as the NZ women's workshop. The girls workshops will be run in collaboration with R-Ladies in places with good travel links where there is a concentration of both volunteers and potential attendees, e.g. San Francisco, London. These will mostly run similarly to the Melbourne workshop, i.e. no
travel and accommodation, just catering for the day. For New Zealand, though, we would like to offer a number of travel bursaries to bring girls from the South Island and more remote locations on the North Island. 

## Other aspects
<!--
Covering non-technical activities like on-going publicity, paper preparation, discussion groups etc. that might be required to facilitate successful delivery of the project.

 - [ ] Announcement post
 - [ ] Delivery blog post
 - [ ] Twitter
 - [ ] UseR!
 - [ ] ISC meetings
-->

The workshops will be advertised through 

- Forwards and R-Ladies twitter 
- the Forwards blog is aggregated by R-Bloggers blog posts, 
- and other sites like RWeekly, the IASC 2017 web site, anzstat mailing list, and with academic institutions, and high schools, directly. Particularly, the team New Zealand has strong communication networks with high school math teachers, by conducting Math Teachers Days annually in Auckland.  

During and following the workshops

- Girls attending the workshops will be encouraged to write about their experiences for the R Consortium blog, publish their app to the RStudio server and give a talk to their peer group at their high school.
- Women at the package development workshop will be encouraged to submit their package to CRAN, and to submit an article on the package to the R Journal.
- The project team will talk about the project and discuss the impact based on metrics and feedback at international conferences like useR! 2018, or the Women in Statistics and Data Science 2018.
- An R Journal publication on the workshops will discuss the process, and success, of the venture. 

